# Generated by Django 5.0.4 on 2024-06-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.CharField(default='N/A', max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='rut_personal',
            field=models.CharField(default='N/A', max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
