# Generated by Django 5.0.4 on 2024-07-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuario_rut_usuario_rut_personal_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('tipo_de_trabajo', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('cuenta_rrss', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
