# Generated by Django 5.0.4 on 2024-07-23 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_ciudad_exalumno_ciudad_desempeno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exalumno',
            old_name='correo_electronico',
            new_name='contacto',
        ),
    ]
