# Generated by Django 5.0.4 on 2024-07-23 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_correo_electronico_exalumno_contacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exalumno',
            old_name='ciudad_desempeno',
            new_name='ciudad',
        ),
    ]
