# Generated by Django 5.0.4 on 2024-07-29 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_ciudad_desempeno_exalumno_ciudad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exalumno',
            name='cuenta_rrss',
        ),
        migrations.RemoveField(
            model_name='exalumno',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='exalumno',
            name='tipo_trabajo',
        ),
    ]
