# Generated by Django 5.0.4 on 2024-07-29 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_exalumno_cuenta_rrss_remove_exalumno_sector_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exalumno',
            old_name='contacto',
            new_name='correo',
        ),
    ]
