# Generated by Django 5.0.4 on 2024-07-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_exalumno_tipo_trabajo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exalumno',
            old_name='nombre',
            new_name='apellidos',
        ),
        migrations.AddField(
            model_name='exalumno',
            name='facebook_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exalumno',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exalumno',
            name='nombres',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
