# Generated by Django 5.0.4 on 2024-08-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_exalumno_correo_alter_exalumno_tipo_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exalumno',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exalumno',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exalumno',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='exalumno',
            name='profesion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
